defaultCashAccount: Assets:FIXME
defaultPositionAccount: Assets:Position:FIXME
defaultCommissionAccount: Expenses:Commission:FIXME
defaultPnlAccount: Income:FIXME
defaultCurrency: CNY
title: 测试
huobi:
  rules:
    - item: BTC/USDT,BTC1S/USDT
      type: 币币交易
      txType: 买入
      fullMatch: true
      sep: ','
      cashAccount: Assets:Rule1:Cash
      positionAccount: Assets:Rule1:Positions
      CommissionAccount: Expenses:Rule1:Commission
      pnlAccount: Income:Rule1:PnL
