defaultMinusAccount: Assets:FIXME
defaultPlusAccount: Expenses:FIXME
defaultCurrency: CNY
title: jd
jd:
  rules:
    - item: 椰子,红薯,膳,食用油,挂面,食盐 # 交易说明
      sep: ","
      targetAccount: Expenses:Food:Snacks
    - category: 美妆个护
      targetAccount: Expenses:MakeUp
    - category: 食品酒饮
      fullMatch: true
      targetAccount: Expenses:Food:Snacks
    - category: 医疗保健
      targetAccount: Expenses:Hospital:Medicine
    - category: 数码电器,电脑办公,手机通讯
      sep: ","
      targetAccount: Expenses:Electronics
    - category: 日用百货,清洁纸品,生活服务,家居家装,其他网购,1号店
      sep: ","
      targetAccount: Expenses:Groceries
    - category: 运动户外
      targetAccount: Expenses:Sports
    - category: 鞋服箱包,服饰内衣
      targetAccount: Expenses:Clothes
    - category: 收发快递
      targetAccount: Expenses:Reside:Express
    - item: 转入
      type: 收入
      targetAccount: Income:Rebate

    - peer: 亲密卡
      targetAccount: Expenses:Prpaid
    - item: 白条,还款
      targetAccount: Liabilities:Baitiao
    - item: 京东小金库收益
      fullMatch: true
      targetAccount: Income:PnL:JD
      methodAccount: Assets:EPay:JD

    - method: 京东白条
      methodAccount: Liabilities:JD:Baitiao
    - method: 小金库零用钱
      methodAccount: Assets:EPay:JD
    - method: 钱包余额
      methodAccount: Assets:JD:Balance
    - method: (0354)
      methodAccount: Liabilities:CC:BCM:0354
    - method: (1341)
      methodAccount: Liabilities:CC:BoC:1341
    - method: (1875)
      methodAccount: Liabilities:CC:BoC:1875
    - method: (2189)
      methodAccount: Liabilities:CC:BoNB:2189
    - method: (0924)
      methodAccount: Liabilities:CC:CMB:0924
    - method: (0073)
      methodAccount: Liabilities:CC:CMBC:0073
    - method: (5559)
      methodAccount: Liabilities:CC:CMBC:5559
    - method: 微信-
      ignore: true
    - method: 先享后付
      ignore: true
    - category: 网购
      type: 不计收支
      targetAccount: Income:Rebate
