defaultMinusAccount: Assets:FIXME
defaultPlusAccount: Expenses:FIXME
defaultCashAccount: Liabilities:Bank:CN:ICBC
defaultCurrency: CNY
title: 测试
icbc:
  rules:
    - peer: 财付通,支付宝
      ignore: true
    - peer: 广东联合电子收费股份
      targetAccount: Expenses:Transport:Highway
    - txType: 人民币自动转帐还款
      targetAccount: Assets:Bank:CN:ICBC:Savings
