source "https://rubygems.org"

# 使用 Jekyll 4.2，它使用 sassc 而不是 sass-embedded
gem "jekyll", "~> 4.2"
gem "webrick"
gem "just-the-docs"
gem "jekyll-feed", "~> 0.15"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-paginate"
