name: goreleaser

# only run on new tag
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Installation Token
        uses: jnwng/github-app-installation-token-action@v2
        id: installationToken
        with: 
          appId: 233273
          installationId: 28742230
          privateKey: ${{ secrets.GH_APP_PRIVATE_KEY }}
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: ~> 1.20
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ steps.installationToken.outputs.token }}
